name: Unzip bitcoinj
on: workflow_dispatch
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip and move
        run: |
          cd wallet/src/wallet/java
          unzip bitcoinj-master.zip
          mv bitcoinj-master/core/src/main/java/org/bitcoinj ./org/
          rm -rf bitcoinj-master.zip bitcoinj-master
          
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add bitcoinj source