name: Unzip JUnit

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: |
          unzip -o junit.zip -d test/wallet/
          rm -f junit.zip

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add JUnit source to test/wallet"