name: Unzip bitcoinj source

on:
  workflow_dispatch: # Bấm tay để chạy

permissions:
  contents: write # Cấp quyền push cho GITHUB_TOKEN

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Unzip and move bitcoinj
        run: |
          cd wallet/src/wallet/java
          unzip bitcoinj-master.zip
          mv bitcoinj-master/core/src/main/java/org./org/
          rm -rf bitcoinj-master.zip bitcoinj-master
          
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add bitcoinj source
          file_pattern: wallet/src/wallet/java/org/
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: buli-net <285223619+buli-net@users.noreply.github.com>