name: Unzip ch.zip

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip ch.zip
        run: |
          cd wallet/src/wallet/java
          unzip -o ch.zip
          rm ch.zip

      - name: Commit unzipped files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Unzip ch.zip - vendor logback"
          file_pattern: wallet/src/wallet/java/ch/**